#!/usr/bin/env node
var buster = require("buster");

buster.testRunner.onCreate(function (runner) {
    runner.on("suite:end", function (results) {
        process.nextTick(function () {
            process.exit(results.ok ? 0 : 1);
        });
    });
});

require("./test/referee-combinators-test");
require("./test/util-test");
require("./test/test-helper-test");
